# -*- conf -*-

font=FiraCode Nerd Font Mono:size=11

[main]
include=/usr/share/foot/themes/noirblaze

[colors]
background=0d0d0f
foreground=ffffff

## custom colors
regular0=0d0d0f
regular1=ff005f
regular2=00ffcc
regular3=f0c040
regular4=005fff
regular5=bf00ff
regular6=00d7ff
regular7=c0c0c0

## Bright colors (custom)
bright0=1a1a2e
bright1=ff3366
bright2=00ffcc
bright3=ffd700
bright4=0087ff
bright5=d700ff
bright6=00ffff
bright7=ffffff

selection-foreground=ffffff
selection-background=00ffcc

[key-bindings]
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up

[url-bindings]
toggle-url-visible=t

# vim: ft=dosini
